### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by bmunkacsy** [thorstenwagner/R-ClustMAPDP#6]
Hi,
I want to use the MAP-DP algorithm for my master's thesis and I was very happy to find this implementation for R. However, when I try to install it, I get an error message:

`install.packages("/path/to/ClustMAPDP_X.tar.gz")` 
> install.packages("/path/to/ClustMAPDP_X.tar.gz")
> Installing` package into ‘C:/Users/Balu/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘/path/to/ClustMAPDP_X.tar.gz’ is not available (for R version 3.5.2)

Is this an issue with my device or the package? Can you give me advice on how to solve it?

**Comment by thorstenwagner** [comment]
Try this
https://github.com/thorstenwagner/R-ClustMAPDP/issues/2#issuecomment-360532348

**Comment by bmunkacsy** [comment]
Thanks! That works.
